include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = NFBPreferences
NFBPreferences_FILES = NFBPreferences.m
NFBPreferences_CFLAGS = -fobjc-arc
NFBPreferences_FRAMEWORKS = UIKit Foundation MobileCoreServices
NFBPreferences_PRIVATE_FRAMEWORKS = Preferences
NFBPreferences_INSTALL_PATH = /Library/PreferenceBundles
NFBPreferences_RESOURCE_DIRS = Resources

include $(THEOS_MAKE_PATH)/bundle.mk
